#!/usr/bin/env bash
# vim: ft=bash ts=2 sw=2 sts=2 et :
 
what=duo
hi() { 
  clear
  tput bold; tput setaf 5
  cat<<-'EOF'
                  ___                       
 __              /\_ \      __              
/\_\     __  __  \//\ \    /\_\      __     
\/\ \   /\ \/\ \   \ \ \   \/\ \   /'__`\   
 \ \ \  \ \ \_\ \   \_\ \_  \ \ \ /\ \L\.\_ 
 _\ \ \  \ \____/   /\____\  \ \_\\ \__/.\_\
/\ \_\ \  \/___/    \/____/   \/_/ \/__/\/_/
\ \____/                                    
 \/___/                                     

	EOF
  tput bold; tput setaf 241
  echo "Short cuts:"
  alias | sed 's/alias /  /'
  echo ""
  tput sgr0
}

here="$(dirname $(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd ))"

#alias bye="gp; tmux detach"
alias gp="git add *;git commit -am save;git push;git status"
alias h="history"
alias="julia -O0 --compile=min --startup=no"

export BASH_SILENCE_DEPRECATION_WARNING=1
export PATH="$PWD:/opt/homebrew/bin:$PATH"
export EDITOR=$(which pico)

here() { cd $1; basename `pwd`; }
#!/usr/bin/env bash

PROMPT_COMMAND='echo -ne "⓻ $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'

hi
